TYPESCRIPT_TRANSLATION = {
    "AutoField": "number",
    "BigAutoField": "number",
    "BigIntegerField": "number",
    "BinaryField": "number",
    "BooleanField": "boolean",
    "CharField": "text",
    "CommaSeparatedIntegerField": "number",
    "DateField": "Date",
    "DateTimeField": "Date",
    "DecimalField": "number",
    "DurationField": "number",
    "EmailField": "text",
    "FilePathField": "text",
    "FloatField": "number",
    "GenericIPAddressField": "text",
    "IPAddressField": "text",
    "IntegerField": "number",
    "NullBooleanField": "boolean | null",
    "PositiveBigIntegerField": "number",
    "PositiveIntegerField": "number",
    "PositiveSmallIntegerField": "number",
    "SlugField": "string",
    "SmallAutoField": "number",
    "SmallIntegerField": "number",
    "TextField": "string",
    "TimeField": "string",
    "URLField": "string",
    "UUIDField": "string",
    "ForeignKey": "number",
    "OneToOneField": "number",
}

FORM_TRANSLATION = {
    "AutoField": {"type": "number"},
    "BigAutoField": {"type": "number"},
    "BigIntegerField": {"type": "number"},
    "BinaryField": {"type": "number"},
    "BooleanField": {"type": "checkbox"},
    "CharField": {"type": "text"},
    "CommaSeparatedIntegerField": {"type": "number"},
    "DateField": {"type": "date"},
    "DateTimeField": {"type": "date"},
    "DecimalField": {"type": "number"},
    "DurationField": {"type": "number"},
    "EmailField": {"type": "text"},
    "FilePathField": {"type": "text"},
    "FloatField": {"type": "number"},
    "GenericIPAddressField": {"type": "text"},
    "IPAddressField": {"type": "text"},
    "IntegerField": {"type": "number"},
    "NullBooleanField": {"type": "checkbox"},
    "PositiveBigIntegerField": {"type": "number"},
    "PositiveIntegerField": {"type": "number"},
    "PositiveSmallIntegerField": {"type": "number"},
    "SlugField": {"type": "text"},
    "SmallAutoField": {"type": "number"},
    "SmallIntegerField": {"type": "number"},
    "TextField": {"type": "text"},
    "TimeField": {"type": "text"},
    "URLField": {"type": "text"},
    "UUIDField": {"type": "text"},
    "ForeignKey": {"type": "number"},
    "OneToOneField": {"type": "number"},
}
